#!/bin/sh

echo ""
echo "========================================="
echo " Post-install checklist"
echo "========================================="
echo ""
echo "Manual steps remaining:"
echo ""
echo "  [ ] gh auth login          — authenticate GitHub CLI"
echo "  [ ] asdf install           — install tool versions from .tool-versions"
echo "  [ ] ssh-keygen -t ed25519  — generate SSH key (then add to GitHub)"
echo ""
echo "========================================="
echo ""
